baseURL = "https://shyengineer.github.io/"
languageCode = "ko-kr"
title = "ê°œë°œÂ·ë¬¼ë¦¬Â·ê²½ì œ ë¸”ë¡œê·¸"
theme = "PaperMod"

[params]
    math = true
    showFullContents = false
    displayFullContent = false
    description = "ë¬¼ë¦¬í•™ê³¼ ê²½ì œí•™ì„ ê³µë¶€í•˜ëŠ” ì—”ì§€ë‹ˆì–´ì˜ ê¸°ë¡ì…ë‹ˆë‹¤." # ê²€ìƒ‰ ê²°ê³¼ ì„¤ëª…
    author = "ShyEngineer"
    googleAnalytics = "G-672600DYET" # ì—¬ê¸°ì— ë°›ì€ IDë¥¼ ë„£ìœ¼ì„¸ìš”!!
    
    [params.homeInfoParams]
        Title = "ë°˜ê°‘ìŠµë‹ˆë‹¤! ğŸ‘‹"
        Content = "ë¬¼ë¦¬, ê²½ì œ, ê·¸ë¦¬ê³  ê°œë°œ ì´ì•¼ê¸°ë¥¼ ë‹¤ë£¹ë‹ˆë‹¤."